# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f294cf3094e78759575d9f3bcd5a03ef17c76ffdf4ce63496c313f6b59836307fc3f418852fea76d49ef1166be83dbd1e9a4a5cb69a239d82efd1f0593d868

test:
  secret_key_base: 1e985b8ad0a879e5e076e9b084117e0285dd3e4195b41ed6371955d93c3e7bfed7caec3b81c0cec4941127845df01a10622514d37a17dba6cda49650ef819bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
